favicon: /images/favicon.ico

logo:
  colorful: true

search:
  enable: true

# showKey：true 或者 false 是指宽屏是否显示文字
navbar:
  menu:
    - { key: "Posts", enable: true, link: "/archives/", icon: "notes", showKey: true}
    - { key: "Github", enable: true, link: "https://github.com/GIN-18", icon: "github", showKey: false}

# Options: 
# palette: frappe, macchiato, mocha
dark_mode:
  palette: mocha

author:
  enable: true
  avatar: /images/avatar.jpg

footer:
  copyright:
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
    license: 'BY-NC-SA'
  start_year: 2023